export interface Qualification {
  id: string; title: string; category: "第二类医疗器械注册" | "第一类医疗器械备案" | "生产经营资质" | "质量体系与知识产权";
  number: string; holder: string; scope: string; note: string;
  issued?: string; expires?: string; productSlug?: string;
}
const holder = "内蒙古子殷科技有限公司";
export const QUALIFICATIONS: Qualification[] = [
  { id: "chcomct-sm", title: "医学图像处理软件", category: "第二类医疗器械注册", number: "内械注准20262210005", holder, issued: "2026-09-09", expires: "2031-09-08", productSlug: "chcomct-sm",
    scope: "用于对符合 DICOM 3.0 标准的 CT、MRI 医学图像进行导入、处理、显示和保存。",
    note: "型号 Chcomct SM，发布版本 2.0。结果仅为医生提供参考意见，不具有自动诊断功能，不能单独用作临床诊疗决策依据。" },
  { id: "osteotomy-guide", title: "定制式3D打印截骨导板", category: "第二类医疗器械注册", number: "内械注准20232040006", holder, issued: "2023-04-10", expires: "2028-04-09", productSlug: "osteotomy-guide",
    scope: "用于特定病人骨科截骨手术中的定位和导向。",
    note: "不与中枢神经系统、血液循环系统及椎间隙接触。非无菌提供，使用前由使用者按产品要求灭菌。2026年1月12日住所变更文件须与注册证共同使用。" },
  { id: "bone-model", title: "定制式3D打印骨模型", category: "第二类医疗器械注册", number: "内械注准20232020009", holder, issued: "2023-07-24", expires: "2028-07-23", productSlug: "bone-model",
    scope: "用于显示骨缺损部位及骨骼表面形态，辅助观察病患骨部位。",
    note: "不带入手术室内使用，不用于内固定钢板术前弯折。具体型号、材料及适用范围以注册证为准。2026年1月12日住所变更文件须与注册证共同使用。" },
  { id: "organ-model", title: "定制式3D打印器官轮廓模型", category: "第二类医疗器械注册", number: "内械注准20232020010", holder, issued: "2023-07-24", expires: "2028-07-23", productSlug: "organ-model",
    scope: "用于显示人体器官病灶或受损部位表面形态，辅助观察病患部位。",
    note: "不带入手术室内使用。具体型号、材料及适用范围以注册证为准。2026年1月12日住所变更文件须与注册证共同使用。" },
  { id: "orthopedic-holder", title: "骨科用夹持器", category: "第一类医疗器械备案", number: "内呼械备20240005", holder,
    scope: "骨科手术中夹持植入物、器械或组织，手术结束后取出体外。",
    note: "非无菌提供，不在内窥镜下使用。产品型号、材料、受托生产企业和完整范围见备案文件。" },
  { id: "thermoplastic-mask", title: "热塑膜", category: "第一类医疗器械备案", number: "内呼械备20230010", holder,
    scope: "用于放射治疗时患者的定位、固定。",
    note: "适用型号、结构组成及使用方式以备案文件和产品说明书为准。" },
  { id: "polymer-splint", title: "医用高分子夹板", category: "第一类医疗器械备案", number: "内呼械备20240002", holder,
    scope: "用于骨折或软组织等损伤的外固定。",
    note: "适用型号、结构组成及使用方式以备案文件和产品说明书为准。" },
  { id: "external-brace", title: "医用外固定支具", category: "第一类医疗器械备案", number: "内呼械备20210003号", holder,
    scope: "用于骨折或软组织等损伤的外固定。",
    note: "适用型号、结构组成及使用方式以备案文件和产品说明书为准。" },
  { id: "production-license", title: "医疗器械生产许可证", category: "生产经营资质", number: "内药监械生产许20230005号", holder, issued: "2023-05-19", expires: "2028-05-18",
    scope: "Ⅱ类：02-15 手术器械—其他器械；04-16 关节外科辅助器械。",
    note: "信息已根据2026年2月28日变更后的许可证及许可变更记录整理。生产地址、生产范围以证件记载为准。" },
  { id: "class-one-production", title: "第一类医疗器械生产备案", category: "生产经营资质", number: "内呼药监械生产备20210002号", holder,
    scope: "第一类医疗器械生产备案，具体生产范围见备案凭证。",
    note: "本项为生产备案，不作为第二类产品注册证或生产许可证的替代。" },
  { id: "operation-license", title: "医疗器械经营许可证", category: "生产经营资质", number: "内呼药监械经营许20240250号", holder, issued: "2024-05-20", expires: "2029-05-19",
    scope: "经营方式：批发。经营范围、经营场所及库房地址见许可证。",
    note: "信息已根据2026年2月28日变更后的许可证整理。" },
  { id: "class-two-operation", title: "第二类医疗器械经营备案", category: "生产经营资质", number: "内呼药监械经营备20240760号", holder,
    scope: "第二类医疗器械批发经营备案，具体经营范围见备案凭证。",
    note: "信息依据日期为2026年2月28日的备案凭证整理。" },
  { id: "iso13485", title: "医疗器械质量管理体系认证", category: "质量体系与知识产权", number: "HXLC24MQMS10011R0S", holder, issued: "2024-04-27", expires: "2027-04-26",
    scope: "GB/T 42061-2022 / ISO 13485:2016。覆盖许可范围内医用外固定支具的生产，以及定制式3D打印截骨导板、器官轮廓模型、骨模型的研发。",
    note: "证载认证机构为北京宏信联诚认证有限公司。认证范围不延伸至所有产品或全部生产活动；持续有效状态以认证机构监督审核及查询结果为准。" },
  { id: "software-copyright", title: "医学3D数字影像建模软件 V2.0 软件著作权", category: "质量体系与知识产权", number: "2021SR0342123", holder, issued: "2021-03-04",
    scope: "计算机软件著作权登记，软件名称为医学3D数字影像建模软件 V2.0。",
    note: "软件著作权证明知识产权登记，不代表医疗器械注册批准，也不替代 Chcomct SM 的产品注册资料。" },
  { id: "data-service-provider", title: "数商证书 · 数据服务商", category: "质量体系与知识产权", number: "NMG2604001", holder, issued: "2026-04-09", expires: "2027-04-09",
    scope: "内蒙古数据要素综合服务中心颁发的数据服务商数商证书。",
    note: "本项说明数据服务商资质，不代表医疗器械产品注册或对患者数据的自动处理授权。" },
];
export const QUALIFICATION_CATEGORIES = ["第二类医疗器械注册", "第一类医疗器械备案", "生产经营资质", "质量体系与知识产权"] as const;
